spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/canteendb?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#mybatis整合
mybatis:
  type-aliases-package: com.cuit.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#解决地址栏sessionid问题
server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
  port: 8181

